# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paranuara_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['company_name'], 
                     'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='index',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
