# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paranuara_api', '0002_enforce_company_uniqueness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodstuff',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('f', 'Fruit'),
                                                   ('v', 'Vegetable')],
                                          max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Foodstuffs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('json_id', models.CharField(max_length=24, unique=True)),
                ('index', models.PositiveIntegerField(unique=True)),
                ('guid', models.CharField(max_length=36, unique=True)),
                ('has_died', models.BooleanField()),
                ('balance', models.DecimalField(decimal_places=2,
                                                max_digits=8)),
                ('picture', models.URLField()),
                ('age', models.PositiveIntegerField()),
                ('eyecolor', models.CharField(choices=[('bl', 'Blue'),
                                                       ('br', 'Brown')],
                                              max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('m', 'Male'),
                                                     ('f', 'Female')],
                                            max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('registered', models.DateTimeField()),
                ('greeting', models.CharField(max_length=100)),
                ('company', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='paranuara_api.Company')),
                ('favourite_food', models.ManyToManyField(
                    to='paranuara_api.Foodstuff')),
                ('friends', models.ManyToManyField(
                    to='paranuara_api.Person')),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(to='paranuara_api.Tag'),
        ),
    ]
