# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paranuara_api', '0003_add_people_tags_foodstuffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.CASCADE, 
                to='paranuara_api.Company'),
        ),
        migrations.AlterField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(
                blank=True, 
                to='paranuara_api.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(
                blank=True, 
                to='paranuara_api.Tag'),
        ),
    ]
